export const Matchups = [
  {
    homeImg: "Seahawks.gif",
    homeAlt: "Seahawks",
    homeRecord: "7-5",
    awayImg: "Vikings.gif",
    awayAlt: "Vikings",
    awayRecord: "6-5-1",
    index: "0",
    yppa_diff: 1,
    rush_diff: 0.6,
    drive_points_diff: 0.5,
    turnover_diff: 15,
    sack_yards_diff: -6.3,
    sack_times_diff: 0.4
  },
  {
    homeImg: "Titans.gif",
    homeAlt: "Titans",
    homeRecord: "6-6",
    awayImg: "Jaguars.gif",
    awayAlt: "Jaguars",
    awayRecord: "4-8",
    index: "1",

    yppa_diff: 1,
    rush_diff: 0.3,
    drive_points_diff: 0.6,
    turnover_diff: -1,
    sack_yards_diff: 0.9,
    sack_times_diff: 1.3
  },
  {
    homeImg: "Browns.gif",
    homeAlt: "Browns",
    homeRecord: "4-7-1",
    awayImg: "Panters.gif",
    awayAlt: "Panters",
    awayRecord: "6-6",
    index: "2",
    yppa_diff: 0.2,
    rush_diff: -0.5,
    drive_points_diff: -0.34,
    turnover_diff: 7,
    sack_yards_diff: 1.9,
    sack_times_diff: 1.3
  },
  {
    homeImg: "Chiefs.gif",
    homeAlt: "Chiefs",
    homeRecord: "10-2",
    awayImg: "Ravens.gif",
    awayAlt: "Ravens",
    awayRecord: "7-5",
    index: "3",
    yppa_diff: 2.1,
    rush_diff: 0.3,
    drive_points_diff: 1.06,
    turnover_diff: 9,
    sack_yards_diff: 3.5,
    sack_times_diff: 0.6
  },
  {
    homeImg: "Texans.gif",
    homeAlt: "Texans",
    homeRecord: "9-3",
    awayImg: "Colts.gif",
    awayAlt: "Colts",
    awayRecord: "6-6",
    index: "4",
    yppa_diff: 1.1,
    rush_diff: 0.1,
    drive_points_diff: -0.35,
    turnover_diff: 13,
    sack_yards_diff: 5.1,
    sack_times_diff: 0.3
  },
  {
    homeImg: "Dolphins.gif",
    homeAlt: "Dolphins",
    homeRecord: "6-6",
    awayImg: "Patriots.gif",
    awayAlt: "Patriots",
    awayRecord: "9-3",
    index: "5",
    yppa_diff: -4,
    rush_diff: 0.4,
    drive_points_diff: -7,
    turnover_diff: 5,
    sack_yards_diff: -1.8,
    sack_times_diff: 0.1
  },
  {
    homeImg: "Redskins.gif",
    homeAlt: "Redskins",
    homeRecord: "6-5",
    awayImg: "Giants.gif",
    awayAlt: "Giants",
    awayRecord: "4-8",
    index: "6",
    yppa_diff: -1.1,
    rush_diff: -0.4,
    drive_points_diff: -0.68,
    turnover_diff: 7,
    sack_yards_diff: 7,
    sack_times_diff: 1
  },
  {
    homeImg: "Bucs.gif",
    homeAlt: "Buccaneers",
    homeRecord: "5-7",
    awayImg: "Saints.gif",
    awayAlt: "Saints",
    awayRecord: "10-2",
    index: "7",
    yppa_diff: 0.6,
    rush_diff: -0.4,
    drive_points_diff: -0.7,
    turnover_diff: -18,
    sack_yards_diff: 5.6,
    sack_times_diff: 0.7
  },
  {
    homeImg: "Packers.gif",
    homeAlt: "Packers",
    homeRecord: "4-7-1",
    awayImg: "Falcons.gif",
    awayAlt: "Falcons",
    awayRecord: "4-8",
    index: "8",
    yppa_diff: -0.8,
    rush_diff: 0.5,
    drive_points_diff: -0.3,
    turnover_diff: 0,
    sack_yards_diff: -7,
    sack_times_diff: 0.4
  },
  {
    homeImg: "Bills.gif",
    homeAlt: "Bills",
    homeRecord: "4-8",
    awayImg: "Jets.gif",
    awayAlt: "Jets",
    awayRecord: "3-9",
    index: "9",
    yppa_diff: -0.3,
    rush_diff: 0.2,
    drive_points_diff: -0.2,
    turnover_diff: -5,
    sack_yards_diff: -4.8,
    sack_times_diff: -0.2
  },
  {
    homeImg: "Chargers.gif",
    homeAlt: "Chargers",
    homeRecord: "9-3",
    awayImg: "Bengals.gif",
    awayAlt: "Bengals",
    awayRecord: "4-7",
    index: "10",
    yppa_diff: 2.2,
    rush_diff: 0,
    drive_points_diff: 0.4,
    turnover_diff: 1,
    sack_yards_diff: 4.2,
    sack_times_diff: 0.25
  },
  {
    homeImg: "Raiders.gif",
    homeAlt: "Raiders",
    homeRecord: "2-10",
    awayImg: "Steelers.gif",
    awayAlt: "Steelers",
    awayRecord: "7-4-1",
    index: "11",
    yppa_diff: -0.2,
    rush_diff: 0,
    drive_points_diff: 0.66,
    turnover_diff: -7,
    sack_yards_diff: -13,
    sack_times_diff: 2.4
  },
  {
    homeImg: "Bears.gif",
    homeAlt: "Bears",
    homeRecord: "8-4",
    awayImg: "Rams.gif",
    awayAlt: "Rams",
    awayRecord: "11-1",
    index: "12",
    yppa_diff: -1,
    rush_diff: -0.8,
    drive_points_diff: -0.6,
    turnover_diff: 12,
    sack_yards_diff: 0.81,
    sack_times_diff: 0.6
  },
  {
    homeImg: "Cardinals.gif",
    homeAlt: "Cardinals",
    homeRecord: "3-9",
    awayImg: "Lions.gif",
    awayAlt: "Lions",
    awayRecord: "4-8",
    index: "13",
    yppa_diff: -0.9,
    rush_diff: -0.3,
    drive_points_diff: -0.7,
    turnover_diff: -12,
    sack_yards_diff: 0.1,
    sack_times_diff: 0.4
  },
  {
    homeImg: "49ers.gif",
    homeAlt: "49ers",
    homeRecord: "2-10",
    awayImg: "Broncos.gif",
    awayAlt: "Broncos",
    awayRecord: "6-6",
    index: "14",
    yppa_diff: 1.3,
    rush_diff: -0.4,
    drive_points_diff: 0.1,
    turnover_diff: -25,
    sack_yards_diff: -5.3,
    sack_times_diff: -0.4
  },
  {
    homeImg: "Cowboys.gif",
    homeAlt: "Cowboys",
    homeRecord: "7-5",
    awayImg: "Eagles.gif",
    awayAlt: "Eagles",
    awayRecord: "5-6",
    index: "15",
    yppa_diff: -0.2,
    rush_diff: 0.6,
    drive_points_diff: 0.1,
    turnover_diff: 3,
    sack_yards_diff: -5.1,
    sack_times_diff: 0.3
  }
];
